name: Android APK Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Free Disk Space (Bellek Hatasını Önlemek İçin)
        run: |
          sudo docker image prune --all --force
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf /usr/local/share/boost /usr/local/lib/node_modules

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git libncurses5 libstdc++6 zlib1g-dev libffi-dev libssl-dev python3-dev python3-pip libgdm-dev libdbus-1-dev openjdk-17-jdk
          pip install --upgrade "Cython<3.0" buildozer

      - name: Build with Buildozer
        run: |
          # Lisansları otomatik onaylar ve derlemeyi başlatır
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kurye-Takip-APK
          path: bin/*.apk
